apiVersion: 1
groups:
  - orgId: 1
    name: ledgerd
    folder: Qazna
    interval: 1m
    rules:
      - uid: ledgerd-account-drop
        title: Ledgerd Account Count Drop
        condition: C
        data:
          - refId: A
            relativeTimeRange: { from: 300, to: 0 }
            datasourceUid: prometheus
            model:
              datasource:
                type: prometheus
                uid: prometheus
              editorMode: code
              expr: max(ledgerd_accounts)
              instant: false
              interval: ""
              intervalFactor: 1
              legendFormat: ""
              maxDataPoints: 43200
              range: true
              refId: A
          - refId: B
            relativeTimeRange: { from: 300, to: 0 }
            datasourceUid: __expr__
            model:
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              reducer: last
              refId: B
              settings:
                mode: last
              type: reduce
          - refId: C
            relativeTimeRange: { from: 300, to: 0 }
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: [1]
                    type: lt
                  operator:
                    type: and
                  query:
                    params: []
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: B
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        noDataState: NoData
        execErrState: Error
        for: 5m
        annotations:
          summary: Ledgerd reported account count below expected threshold
        labels:
          severity: critical
      - uid: ledgerd-transfer-flatline
        title: Ledgerd Transfer Flatline
        condition: C
        data:
          - refId: A
            relativeTimeRange: { from: 600, to: 0 }
            datasourceUid: prometheus
            model:
              datasource:
                type: prometheus
                uid: prometheus
              editorMode: code
              expr: sum(rate(ledgerd_transfers_total[5m]))
              instant: false
              interval: ""
              intervalFactor: 1
              legendFormat: ""
              maxDataPoints: 43200
              range: true
              refId: A
          - refId: B
            relativeTimeRange: { from: 600, to: 0 }
            datasourceUid: __expr__
            model:
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              reducer: last
              refId: B
              settings:
                mode: last
              type: reduce
          - refId: C
            relativeTimeRange: { from: 600, to: 0 }
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: [0.01]
                    type: lt
                  operator:
                    type: and
                  query:
                    params: []
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: B
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        noDataState: NoData
        execErrState: Error
        for: 10m
        annotations:
          summary: Ledgerd transfer throughput has been below 0.01 tx/s for 10m
        labels:
          severity: warning
