{
 "title": "Qazna API",
 "panels": [
  {
   "title": "In-Flight Requests",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 6 },
   "targets": [
    { "expr": "http_inflight_requests" }
   ]
  },
  {
   "title": "HTTP Requests Rate",
   "type": "graph",
   "gridPos": { "x": 6, "y": 0, "w": 18, "h": 6 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])" }
   ]
  },
  {
   "title": "Latency (histogram)",
   "type": "heatmap",
   "gridPos": { "x": 0, "y": 6, "w": 24, "h": 9 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket[1m])) by (le)"
    }
   ]
  }
 ]
}