# ops/prometheus.yml
global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'qazna-api'
    static_configs:
      - targets: ['qazna-api:8080']
  - job_name: 'ledgerd'
    static_configs:
      - targets: ['ledgerd:9102']

rule_files:
  - /etc/prometheus/rules/qazna.rules.yml
