# .github/workflows/ci.yml
name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run docker compose
        env:
          # Передаем секреты из GitHub Secrets в переменные окружения
          QAZNA_AUTH_PRIVATE_KEY: ${{ secrets.QAZNA_AUTH_PRIVATE_KEY }}
          QAZNA_AUTH_PUBLIC_KEY: ${{ secrets.QAZNA_AUTH_PUBLIC_KEY }}
          QAZNA_AUTH_SECRET: ${{ secrets.QAZNA_AUTH_SECRET || 'test-secret' }}
          # Для тестов можно использовать простые пароли
          QAZNA_POSTGRES_PASSWORD: test-password
          QAZNA_GRAFANA_ADMIN_PASSWORD: test-password
        run: docker compose up -d --build

      - name: Wait for services to be healthy
        run: |
          sleep 15
          docker compose ps
          curl -s --fail http://localhost:8080/healthz

      - name: Run local tests
        run: make test
