name: Terraform Check

on:
  pull_request:
    paths:
      - 'ops/infra/**'
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.2

      - name: Terraform fmt
        run: terraform -chdir=ops/infra/environments/dev fmt -check

      - name: Terraform validate
        run: terraform -chdir=ops/infra/environments/dev validate

      - name: Terraform plan
        env:
          TF_IN_AUTOMATION: 1
        run: |
          terraform -chdir=ops/infra/environments/dev init -backend=false
          terraform -chdir=ops/infra/environments/dev plan -out=plan.out -var project_id=dummy-project
          terraform -chdir=ops/infra/environments/dev show -json plan.out > tfplan.json

      - name: Install OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: latest

      - name: Evaluate OPA policies
        run: |
          opa eval --format pretty --fail-defined --data ops/policies --input ops/infra/environments/dev/tfplan.json "data.terraform.deny"
